### ISSUE TITLE
Did you get this to work?

### ISSUE THREAD

**Issue by ZeFoxii** [radiomanV/Tiny-GBS#1]
Could you provide pictures of what the finished project looks like?

**Comment by radiomanV** [comment]
This was a project shared in a google group dedicated to some spectrum clones.
The idea was to modify an existing spare old monitor (samsung syncmaster 720N) by adapting a modified GBS-8220 board inside the monitor case.
That was done by removing all unnecessary connectors and parts from the gbs board and solder the programmed attiny chip directly to the old 24c eeprom pcb pads.

The attiny chip will only program the internal registers of the gbs chip via i2c bus at each power up.

Some pictures can be viewed here: 
https://groups.google.com/g/romanianhomecomputer/c/oGzIk7s7TQA

The group is not in English language, but you can use g. translate or ask me here if you don't understand something.

**Comment by radiomanV** [comment]
No ressponse from op, closed.
